const elencoCorinthians2024 = [
    {
        'nome': 'Hugo Souza',
        'idade': '25 anos',
        'jogos': 34,
        'gols sofridos': 34,
        'jogos sem sofrer gol': 12,
    },
    {
        'nome': 'Matheus Donelli',
        'idade': '22 anos',
        'jogos': 7,
        'gols sofridos': 12,
        'jogos sem sofrer gol': 0,
    },
    {
        'nome': 'Félix Torres',
        'idade': '27 anos',
        'jogos': 52,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Cacá',
        'idade': '25 anos',
        'jogos': 39,
        'gols': 6,
        'assistencias': 1,
    },
    {
        'nome': 'André Ramalho',
        'idade': '32 anos',
        'jogos': 29,
        'gols': 1,
        'assistencias': 1,
    },
    {
        'nome': 'Caetano',
        'idade': '25 anos',
        'jogos': 15,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Gustavo Henrique',
        'idade': '31 anos',
        'jogos': 35,
        'gols': 2,
        'assistencias': 0,
    },
    {
        'nome': 'Matheus Bidu',
        'idade': '25 anos',
        'jogos': 33,
        'gols': 2,
        'assistencias': 2,
    },
    {
        'nome': 'Diego Palacios',
        'idade': '25 anos',
        'jogos': 1,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Hugo',
        'idade': '27 anos',
        'jogos': 51,
        'gols': 0,
        'assistencias': 4,
    },
    {
        'nome': 'Matheuzinho',
        'idade': '24 anos',
        'jogos': 41,
        'gols': 2,
        'assistencias': 1,
    },
    {
        'nome': 'Léo Mana',
        'idade': '20 anos',
        'jogos': 9,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Fagner',
        'idade': '35 anos',
        'jogos': 41,
        'gols': 0,
        'assistencias': 5,
    },
    {
        'nome': 'Igor Coronado',
        'idade': '32 anos',
        'jogos': 45,
        'gols': 4,
        'assistencias': 5,
    },
    {
        'nome': 'Rodrigo Garro',
        'idade': '26 anos',
        'jogos': 62,
        'gols': 13,
        'assistencias': 14
    },
    {
        'nome': 'André Carrillo',
        'idade': '33 anos',
        'jogos': 19,
        'gols': 0,
        'assistencias': 2,
    },
    {
        'nome': 'Charles',
        'idade': '28 anos',
        'jogos': 24,
        'gols': 1,
        'assistencias': 0,
    },
    {
        'nome': 'Alex Santana',
        'idade': '29 anos',
        'jogos': 15,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Maycon',
        'idade': '27 anos',
        'jogos': 13,
        'gols': 2,
        'assistencias': 2,
    },
    {
        'nome': 'Breno Bidon',
        'idade': '19 anos',
        'jogos': 44,
        'gols': 1,
        'assistencias': 2,
    },
    {
        'nome': 'Ryan',
        'idade': '21 anos',
        'jogos': 22,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'José Martínez',
        'idade': '30 anos',
        'jogos': 11,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Raniele',
        'idade': '27 anos',
        'jogos': 57,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Ruan Oliveira',
        'idade': '24 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Matheus Araújo',
        'idade': '22 anos',
        'jogos': 12,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Yuri Alberto',
        'idade': '23 anos',
        'jogos': 57,
        'gols': 31,
        'assistencias': 7,
    },
    {
        'nome': 'Memphis Depay',
        'idade': '30 anos',
        'jogos': 14,
        'gols': 7,
        'assistencias': 4,
    },
    {
        'nome': 'Angel Romero',
        'idade': '32 anos',
        'jogos': 59,
        'gols': 14,
        'assistencias': 8,
    },
    {
        'nome': 'Héctor Hernández',
        'idade': '29 anos',
        'jogos': 5,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Pedro Raul',
        'idade': '28 anos',
        'jogos': 32,
        'gols': 3,
        'assistencias': 1,        
    },
    {
        'nome': 'Giovane',
        'idade': '21 anos',
        'jogos': 21,
        'gols': 2,
        'assistencias': 0,
    },
    {
        'nome': 'Pedro Henrique',
        'idade': '34 anos',
        'jogos': 26,
        'gols': 2,
        'assistencias': 1,
    },
    {
        'nome': 'Talles Magno',
        'idade': '22 anos',
        'jogos': 19,
        'gols': 3,
        'assistencias': 3,
    },
];

export default elencoCorinthians2024;