const elencoCorinthians = [
    {
        'nome': 'Hugo Souza',
        'idade': '25 anos',
        'jogos': 0,
        'gols sofridos': 0,
        'jogos sem sofrer gol': 0,
    },
    {
        'nome': 'Matheus Donelli',
        'idade': '22 anos',
        'jogos': 0,
        'gols sofridos': 0,
        'jogos sem sofrer gol': 0,
    },
    {
        'nome': 'Félix Torres',
        'idade': '27 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Cacá',
        'idade': '25 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'André Ramalho',
        'idade': '32 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Gustavo Henrique',
        'idade': '31 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Matheus Bidu',
        'idade': '25 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Diego Palacios',
        'idade': '25 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Hugo',
        'idade': '27 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Matheuzinho',
        'idade': '24 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Léo Mana',
        'idade': '20 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Fagner',
        'idade': '35 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Igor Coronado',
        'idade': '32 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Rodrigo Garro',
        'idade': '26 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'André Carrillo',
        'idade': '33 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Charles',
        'idade': '28 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Alex Santana',
        'idade': '29 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Maycon',
        'idade': '27 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Breno Bidon',
        'idade': '19 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Ryan',
        'idade': '21 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'José Martínez',
        'idade': '30 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Raniele',
        'idade': '27 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Ruan Oliveira',
        'idade': '24 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Yuri Alberto',
        'idade': '23 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Memphis Depay',
        'idade': '30 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Angel Romero',
        'idade': '32 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Héctor Hernández',
        'idade': '29 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Pedro Raul',
        'idade': '28 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,        
    },
    {
        'nome': 'Giovane',
        'idade': '21 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Talles Magno',
        'idade': '22 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
];

export default elencoCorinthians;