const meiasCorinthians = [
    {
        'nome': 'Igor Coronado',
        'idade': '32 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Rodrigo Garro',
        'idade': '26 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'André Carrillo',
        'idade': '33 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Charles',
        'idade': '28 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Alex Santana',
        'idade': '29 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Maycon',
        'idade': '27 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Breno Bidon',
        'idade': '19 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Ryan',
        'idade': '21 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'José Martínez',
        'idade': '30 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Raniele',
        'idade': '27 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
    {
        'nome': 'Ruan Oliveira',
        'idade': '24 anos',
        'jogos': 0,
        'gols': 0,
        'assistencias': 0,
    },
];

export default meiasCorinthians;